{
 "title": "Pizza Deliverable",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "dev, prod" }
  ]
 },
 "panels": [
  {
   "title": "New Panel",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-deliverable-dev\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Pizza Creation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pizza_transactions{source=~\"jwt-pizza-deliverable-${environment}|jwt-pizza-deliverable-dev\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(pizza_money{source=~\"jwt-pizza-deliverable-dev|jwt-pizza-deliverable-${environment}\"}[60m])",
     "legendFormat": "{{Revenue:}}"
    }
   ]
  },
  {
   "title": "Auth Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "auth_total{source=~\"jwt-pizza-deliverable-${environment}|jwt-pizza-deliverable-dev\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "latency_average{source=~\"jwt-pizza-deliverable-${environment}|jwt-pizza-deliverable-dev\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "request_total{source=~\"jwt-pizza-deliverable-${environment}|jwt-pizza-deliverable-dev\", type=~\".+\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "user_total{source=~\"jwt-pizza-deliverable-${environment}|jwt-pizza-deliverable-dev\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{source=~\"jwt-pizza-deliverable-${environment}|jwt-pizza-deliverable-dev\", type=\"memory\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{source=~\"jwt-pizza-deliverable-${environment}|jwt-pizza-deliverable-dev\", type=\"cpu\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}